select 'SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM '||TABLE_NAME||'
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);' from user_tables where table_name in (select table_name from user_tables) and table_name not like 'MD%' and not like '%CL_%' ;

SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_WATER_NODE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_WATER_LINK
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_TIDAL_MEASURE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TR_VEHICULAR
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TR_TRANSPORT_NODE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TR_TRANSPORT_LINK
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM SI_SITE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM LF_LEGACY_POLYGON
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM AI_ADV_INTEL_POLYGON
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM AI_ADV_INTEL_POINT
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM AI_ADV_INTEL_LINE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM AB_ADMIN_UNIT
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_WATER_COURSE_POLYGON
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_WATER_COURSE_LINE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_STAND_WATER_POLYGON
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM WA_STAND_WATER_LINE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TR_TRANSPORT_CASING
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TR_NON_VEHICULAR
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM TE_TEXT
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM ST_STRUCTURE_POLYGON
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM ST_STRUCTURE_POINT
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM ST_STRUCTURE_LINE
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM LIS_LAND_INTER_SEA
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM GC_GROUND_COVER
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM PE_PERIMETER
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
 SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM LP_LAND_PARCEL
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
 SELECT COUNT (*), SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001) ERROR_CODE FROM BU_BUILDING
 GROUP BY SDO_GEOM.VALIDATE_GEOMETRY(GEOM, 0.001);
 