# Load Needed Libraries

library(compare)
library(data.table)
library(dplyr)
library(httr)
library(jsonlite)
library(ukboundaries)
library(mapview)
library(oneminutetrafficdata)
library(plyr)
library(RCurl)
library(rgdal)
library(sf)
library(stplanr)
library(stringr)