# Load Needed Libraries

library(compare)
library(data.table)
library(dplyr)
library(ggplot2)
library(ggmap)
library(gridExtra)
library(httr)
library(jsonlite)
library(lubridate)
library(mapview)
library(oneminutetrafficdata)
library(plyr)
library(RCurl)
library(rgdal)
library(sp)
library(spatstat)
library(sf)
library(stplanr)
library(stringr)
library(ukboundaries)
